apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-learn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gzd2032/learn-argo
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fullstack-learn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
