apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-vite-deployment
spec:
  replicas: 1 # default replica count
  template:
    spec:
      containers:
      - name: my-vite
        image: vite-project
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"