apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      kind: Deployment
      name: myapp-deployment
    patch: |
      - op: add
        path: /spec/template/metadata/labels/app
        value: frontend