apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1 # default replica count
  selector:
    matchLabels:
      app: my-vite
  template:
    metadata:
      labels:
        app: my-vite
    spec:
      containers:
      - name: my-vite
        image: vite-project
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"